const irregularVerbs = [
    { verb: "arise", simplePast: "arose", pastParticiple: "arisen", meaning: "surgir, erguer-se, aparecer" },
    { verb: "awake", simplePast: "awoke", pastParticiple: "awoken", meaning: "despertar, acordar" },
    { verb: "be", simplePast: "was, were", pastParticiple: "been", meaning: "ser, estar" },
    { verb: "bear", simplePast: "bore", pastParticiple: "borne*", meaning: "suportar, aguentar, tolerar, resistir, carregar, dar à luz" },
    { verb: "beat", simplePast: "beat", pastParticiple: "beaten", meaning: "bater, agredir, derrotar" },
    { verb: "become", simplePast: "became", pastParticiple: "become", meaning: "tornar-se" },
    { verb: "begin", simplePast: "began", pastParticiple: "begun", meaning: "começar" },
    { verb: "behold", simplePast: "beheld", pastParticiple: "beheld", meaning: "contemplar, observar" },
    { verb: "bend", simplePast: "bent", pastParticiple: "bent", meaning: "curvar, inclinar-se" },
    { verb: "bid", simplePast: "bid", pastParticiple: "bid", meaning: "oferecer, fazer um lance" },
    { verb: "bind", simplePast: "bound", pastParticiple: "bound", meaning: "amarrar, enfaixar, encadernar, obrigar" },
    { verb: "bite", simplePast: "bit", pastParticiple: "bitten", meaning: "morder" },
    { verb: "bleed", simplePast: "bled", pastParticiple: "bled", meaning: "sangrar" },
    { verb: "blow", simplePast: "blew", pastParticiple: "blown", meaning: "assoprar, explodir, estourar" },
    { verb: "break", simplePast: "broke", pastParticiple: "broken", meaning: "quebrar" },
    { verb: "breed", simplePast: "bred", pastParticiple: "bred", meaning: "procriar, reproduzir" },
    { verb: "bring", simplePast: "brought", pastParticiple: "brought", meaning: "trazer" },
    { verb: "build", simplePast: "built", pastParticiple: "built", meaning: "construir" },
    { verb: "burn", simplePast: "burned/burnt", pastParticiple: "burned/burnt", meaning: "queimar" },
    { verb: "buy", simplePast: "bought", pastParticiple: "bought", meaning: "comprar" },
    { verb: "catch", simplePast: "caught", pastParticiple: "caught", meaning: "agarrar, pegar, capturar" },
    { verb: "choose", simplePast: "chose", pastParticiple: "chosen", meaning: "escolher" },
    { verb: "cling", simplePast: "clung", pastParticiple: "clung", meaning: "prender-se, grudar, segurar-se" },
    { verb: "come", simplePast: "came", pastParticiple: "come", meaning: "vir" },
    { verb: "creep", simplePast: "crept", pastParticiple: "crept", meaning: "rastejar, mover-se furtivamente" },
    { verb: "deal", simplePast: "dealt", pastParticiple: "dealt", meaning: "negociar, tratar, distribuir cartas" },
    { verb: "dig", simplePast: "dug", pastParticiple: "dug", meaning: "cavar" },
    { verb: "do", simplePast: "did", pastParticiple: "done", meaning: "fazer" },
    { verb: "draw", simplePast: "drew", pastParticiple: "drawn", meaning: "desenhar, sacar, atrair, empatar" },
    { verb: "dream", simplePast: "dreamed/dreamt", pastParticiple: "dreamed/dreamt", meaning: "sonhar" },
    { verb: "drink", simplePast: "drank", pastParticiple: "drunk", meaning: "beber, tomar" },
    { verb: "drive", simplePast: "drove", pastParticiple: "driven", meaning: "dirigir" },
    { verb: "dwell", simplePast: "dwelled/dwelt", pastParticiple: "dwelled/dwelt", meaning: "residir, ficar em um pensamento" },
    { verb: "eat", simplePast: "ate", pastParticiple: "eaten", meaning: "comer" },
    { verb: "fall", simplePast: "fell", pastParticiple: "fallen", meaning: "cair" },
    { verb: "feed", simplePast: "fed", pastParticiple: "fed", meaning: "alimentar" },
    { verb: "feel", simplePast: "felt", pastParticiple: "felt", meaning: "sentir(-se)" },
    { verb: "fight", simplePast: "fought", pastParticiple: "fought", meaning: "lutar" },
    { verb: "find", simplePast: "found", pastParticiple: "found", meaning: "achar, encontrar, descobrir" },
    { verb: "fit", simplePast: "fitted/fit", pastParticiple: "fitted/fit", meaning: "servir, ajustar, adaptar, caber" },
    { verb: "flee", simplePast: "fled", pastParticiple: "fled", meaning: "fugir" },
    { verb: "fling", simplePast: "flung", pastParticiple: "flung", meaning: "arremessar" },
    { verb: "fly", simplePast: "flew", pastParticiple: "flown", meaning: "voar, pilotar" },
    { verb: "forbid", simplePast: "forbade", pastParticiple: "forbidden", meaning: "proibir" },
    { verb: "forget", simplePast: "forgot", pastParticiple: "forgotten", meaning: "esquecer" },
    { verb: "forgive", simplePast: "forgave", pastParticiple: "forgiven", meaning: "perdoar" },
    { verb: "forsake", simplePast: "forsook", pastParticiple: "forsaken", meaning: "abandonar, largar" },
    { verb: "freeze", simplePast: "froze", pastParticiple: "frozen", meaning: "congelar, paralisar" },
    { verb: "get", simplePast: "got", pastParticiple: "gotten/got", meaning: "**" },
    { verb: "give", simplePast: "gave", pastParticiple: "given", meaning: "dar" },
    { verb: "go", simplePast: "went", pastParticiple: "gone", meaning: "ir" },
    { verb: "grind", simplePast: "ground", pastParticiple: "ground", meaning: "moer" },
    { verb: "grow", simplePast: "grew", pastParticiple: "grown", meaning: "crescer, cultivar" },
    { verb: "hang", simplePast: "hung", pastParticiple: "hung", meaning: "pendurar" },
    { verb: "have", simplePast: "had", pastParticiple: "had", meaning: "ter, beber, comer" },
    { verb: "hear", simplePast: "heard", pastParticiple: "heard", meaning: "ouvir" },
    { verb: "hide", simplePast: "hid", pastParticiple: "hidden", meaning: "esconder" },
    { verb: "hold", simplePast: "held", pastParticiple: "held", meaning: "segurar, armazenar, aguardar" },
    { verb: "keep", simplePast: "kept", pastParticiple: "kept", meaning: "guardar, manter" },
    { verb: "kneel", simplePast: "kneeled/knelt", pastParticiple: "kneeled/knelt", meaning: "ajoelhar-se" },
    { verb: "know", simplePast: "knew", pastParticiple: "known", meaning: "saber, conhecer" },
    { verb: "lay", simplePast: "laid", pastParticiple: "laid", meaning: "colocar(em posição horizontal), botar(ovos)" },
    { verb: "lead", simplePast: "led", pastParticiple: "led", meaning: "liderar, conduzir" },
    { verb: "leap", simplePast: "leaped/leapt", pastParticiple: "leaped/leapt", meaning: "saltar, pular" },
    { verb: "learn", simplePast: "learned/learnt", pastParticiple: "learned/learnt", meaning: "aprender, ficar sabendo" },
    { verb: "leave", simplePast: "left", pastParticiple: "left", meaning: "deixar, partir" },
    { verb: "lend", simplePast: "lent", pastParticiple: "lent", meaning: "emprestar" },
    { verb: "let", simplePast: "let", pastParticiple: "let", meaning: "permitir, deixar" },
    { verb: "lie", simplePast: "lay", pastParticiple: "lain", meaning: "deitar-se" },
    { verb: "light", simplePast: "lit", pastParticiple: "lit", meaning: "acender, iluminar" },
    { verb: "lose", simplePast: "lost", pastParticiple: "lost", meaning: "perder" },
    { verb: "make", simplePast: "made", pastParticiple: "made", meaning: "fazer, fabricar" },
    { verb: "mean", simplePast: "meant", pastParticiple: "meant", meaning: "significar, querer, dizer, ter a intenção de" },
    { verb: "meet", simplePast: "met", pastParticiple: "met", meaning: "encontrar, conhecer(pela primeira vez)" },
    { verb: "misunderstand", simplePast: "misunderstood", pastParticiple: "misunderstood", meaning: "entender mal, interpretar mal" },
    { verb: "overcome", simplePast: "overcame", pastParticiple: "overcome", meaning: "superar" },
    { verb: "overtake", simplePast: "overtook", pastParticiple: "overtaken", meaning: "ultrapassar" },
    { verb: "partake", simplePast: "partook", pastParticiple: "partaken", meaning: "participar" },
    { verb: "pay", simplePast: "paid", pastParticiple: "paid", meaning: "pagar" },
    { verb: "prove", simplePast: "proved", pastParticiple: "proved/proven", meaning: "provar, comprovar" },
    { verb: "read", simplePast: "read", pastParticiple: "read", meaning: "ler" },
    { verb: "ride", simplePast: "rode", pastParticiple: "ridden", meaning: "andar(de bicicleta, moto, a cavalo)" },
    { verb: "ring", simplePast: "rang", pastParticiple: "rung", meaning: "tocar(campainha, sino, etc), telefonar" },
    { verb: "rise", simplePast: "rose", pastParticiple: "risen", meaning: "subir, erguer-se" },
    { verb: "run", simplePast: "ran", pastParticiple: "run", meaning: "correr, concorrer, dirigir(comércio)" },
    { verb: "saw", simplePast: "sawed", pastParticiple: "sawn/sawed", meaning: "serrar" },
    { verb: "say", simplePast: "said", pastParticiple: "said", meaning: "dizer" },
    { verb: "see", simplePast: "saw", pastParticiple: "seen", meaning: "ver" },
    { verb: "seek", simplePast: "sought", pastParticiple: "sought", meaning: "procurar, desejar, correr atrás" },
    { verb: "sell", simplePast: "sold", pastParticiple: "sold", meaning: "vender" },
    { verb: "send", simplePast: "sent", pastParticiple: "sent", meaning: "mandar" },
    { verb: "sew", simplePast: "sewed", pastParticiple: "sewn", meaning: "costurar, coser" },
    { verb: "shake", simplePast: "shook", pastParticiple: "shaken", meaning: "sacudir, tremer" },
    { verb: "shine", simplePast: "shone", pastParticiple: "shone", meaning: "brilhar, reluzir" },
    { verb: "shoot", simplePast: "shot", pastParticiple: "shot", meaning: "atirar, disparar, fotografar, filmar, alvejar" },
    { verb: "show", simplePast: "showed", pastParticiple: "shown/showed", meaning: "mostrar, exibir" },
    { verb: "shrink", simplePast: "shrank", pastParticiple: "shrunk", meaning: "encolher, contrair" },
    { verb: "sing", simplePast: "sang", pastParticiple: "sung", meaning: "cantar" },
    { verb: "sink", simplePast: "sank", pastParticiple: "sunk", meaning: "afundar, submergir" },
    { verb: "sit", simplePast: "sat", pastParticiple: "sat", meaning: "sentar" },
    { verb: "slay", simplePast: "slew", pastParticiple: "slain", meaning: "matar, assassinar" },
    { verb: "sleep", simplePast: "slept", pastParticiple: "slept", meaning: "dormir" },
    { verb: "slide", simplePast: "slid", pastParticiple: "slid", meaning: "deslizar, escorregar" },
    { verb: "sling", simplePast: "slung", pastParticiple: "slung", meaning: "atirar, arremessar" },
    { verb: "smell", simplePast: "smelled/smelt", pastParticiple: "smelled/smelt", meaning: "cheirar, farejar, feder" },
    { verb: "sow", simplePast: "sowed", pastParticiple: "sown", meaning: "semear" },
    { verb: "speak", simplePast: "spoke", pastParticiple: "spoken", meaning: "falar" },
    { verb: "speed", simplePast: "sped", pastParticiple: "sped", meaning: "disparar, acelerar, apressar(-se)" },
    { verb: "spell", simplePast: "spelt", pastParticiple: "spelt", meaning: "soletrar" },
    { verb: "spend", simplePast: "spent", pastParticiple: "spent", meaning: "gastar" },
    { verb: "spill", simplePast: "spilled/spilt", pastParticiple: "spilled/spilt", meaning: "derramar" },
    { verb: "spin", simplePast: "spun/span", pastParticiple: "spun", meaning: "girar, rodar, fiar" },
    { verb: "spit", simplePast: "spit/spat", pastParticiple: "spit/spat", meaning: "cuspir" },
    { verb: "spoil", simplePast: "spoilt", pastParticiple: "spoilt", meaning: "estragar, destruir, mimar" },
    { verb: "spring", simplePast: "sprang/sprung", pastParticiple: "sprung", meaning: "saltar" },
    { verb: "stand", simplePast: "stood", pastParticiple: "stood", meaning: "parar de pé, aguentar" },
    { verb: "steal", simplePast: "stole", pastParticiple: "stolen", meaning: "roubar, furtar" },
    { verb: "stick", simplePast: "stuck", pastParticiple: "stuck", meaning: "cravar, fincar, enfiar, grudar" },
    { verb: "sting", simplePast: "stung", pastParticiple: "stung", meaning: "picar(inseto)" },
    { verb: "stink", simplePast: "stank", pastParticiple: "stunk", meaning: "cheirar mal" },
    { verb: "strew", simplePast: "strewed", pastParticiple: "strewed/strewn", meaning: "espalhar" },
    { verb: "stride", simplePast: "strode", pastParticiple: "stridden", meaning: "andar a passos largos" },
    { verb: "strike", simplePast: "struck", pastParticiple: "struck", meaning: "golpear, desferir, entrar em greve" },
    { verb: "string", simplePast: "strung", pastParticiple: "strung", meaning: "encordar, amarrar" },
    { verb: "strive", simplePast: "strove", pastParticiple: "striven", meaning: "esforçar-se, lutar" },
    { verb: "swear", simplePast: "swore", pastParticiple: "sworn", meaning: "jurar, prometer, assegurar, dizer palavrão" },
    { verb: "sweep", simplePast: "swept", pastParticiple: "swept", meaning: "varrer" },
    { verb: "swell", simplePast: "swelled", pastParticiple: "swollen", meaning: "inchar(-se), crescer, encher(os pneus)" },
    { verb: "swim", simplePast: "swam", pastParticiple: "swum", meaning: "nadar" },
    { verb: "swing", simplePast: "swung", pastParticiple: "swung", meaning: "balançar, alternar" },
    { verb: "take", simplePast: "took", pastParticiple: "taken", meaning: "pegar, tomar" },
    { verb: "teach", simplePast: "taught", pastParticiple: "taught", meaning: "ensinar, dar aula" },
    { verb: "tear", simplePast: "tore", pastParticiple: "torn", meaning: "rasgar, despedaçar" },
    { verb: "tell", simplePast: "told", pastParticiple: "told", meaning: "dizer, contar" },
    { verb: "think", simplePast: "thought", pastParticiple: "thought", meaning: "pensar" },
    { verb: "thrive", simplePast: "throve", pastParticiple: "thriven", meaning: "prosperar(negócio), crescer com saúde" },
    { verb: "throw", simplePast: "threw", pastParticiple: "thrown", meaning: "atirar, arremessar" },
    { verb: "tread", simplePast: "trod", pastParticiple: "trodden", meaning: "pisar, trilhar" },
    { verb: "undergo", simplePast: "underwent", pastParticiple: "undergone", meaning: "submeter-se a, suportar" },
    { verb: "understand", simplePast: "understood", pastParticiple: "understood", meaning: "entender" },
    { verb: "uphold", simplePast: "upheld", pastParticiple: "upheld", meaning: "sustentar, apoiar, defender" },
    { verb: "wake", simplePast: "woke", pastParticiple: "woken", meaning: "acordar" },
    { verb: "wear", simplePast: "wore", pastParticiple: "worn", meaning: "vestir, usar" },
    { verb: "weave", simplePast: "wove", pastParticiple: "woven", meaning: "tecer, trançar" },
    { verb: "weep", simplePast: "wept", pastParticiple: "wept", meaning: "chorar" },
    { verb: "win", simplePast: "won", pastParticiple: "won", meaning: "vencer, ganhar" },
    { verb: "wind", simplePast: "wound", pastParticiple: "wound", meaning: "enrolar, rodar, dar corda" },
    { verb: "wring", simplePast: "wrung", pastParticiple: "wrung", meaning: "torcer" },
    { verb: "write", simplePast: "wrote", pastParticiple: "written", meaning: "escrever" }
]